Task-2-2
wellsky/nmedia pull request #1
Opened 2021-04-29 18:34 UTC by wellsky

2021-05-02 10:42 UTC, maks1596 requested changes

2021-05-02 10:42 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/repository/PostRepositoryInMemory.kt
> +        10099997,
Сделайте, пожалуйста, все параметры именованными.
1. Вам не придётся помнить их порядок
2. Вы случайно не перепутаете, например, количество просмотров с количеством лайков.
3. Код будет легче читать не только в IDE, где автоматически подсвечивается имена параметров. Например, GitHub не подсказывает что именно означает каждая константа

2021-05-02 10:42 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/repository/PostRepositoryInMemory.kt
> +        post = post.copy(
Зачем Вам отдельно держать свойство `post`, когда оно всегда доступно через `data.value`? При текущем подходе Вы дублируете данные => Можно обновить значение `post`, но не произвести операцию `data.value = post`.

2021-05-02 10:42 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/repository/PostRepository.kt
>      fun get(): LiveData<Post>
Поменяйте на `val data: LiveData<Post>` 😉

2021-05-02 10:42 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/viewmodel/PostViewModel.kt
> +    fun like() = repository.like()
Лучше именовать методы такого промежуточного слоя (`ViewModel`, `Presenter`, `Controller`) не в повелительном наклонении (`like`, `share`, `view`), а в уведомительном. Например, `onLikeButtonClicked` и тому подобное. Согласно всем `MV*` паттернам слой `View` не принимает решения, но уведомляет о событиях, произведённых пользователем. От сюда и соответствующие названия методов

2021-05-02 10:42 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/viewmodel/PostViewModel.kt
> +    val data = repository.get()
В данном вариант сгенерируется примерно следующий код:
```kotlin
private val _data = repository.get()
fun getData() = _data
```

Если заменить на вариант
```suggestion
    val data get() = repository.get()
```
то сгенерируется только `fun getData() = repositor.get()`, что производительней, в два раза меньше и лучше отражает наши намерения.

P.S.: Если в `repository` замените функцию на на свойство, то можно будет даже заменить на следующую запись.
```suggestion
    val data by repository::data
```
Я это не часто практикую. Может быть с функцией тоже сработает - проверьте.

2021-05-06 11:05 UTC, wellsky commented on app/src/main/java/ru/netology/nmedia/repository/PostRepositoryInMemory.kt
> +        post = post.copy(
Подскажите, имеется ввиду заменить код функции на такой?
```
    override fun view() {
        data.value = data.value?.copy(
            views = data.value!!.views + 1
        )
    }
```

2021-05-07 21:15 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/repository/PostRepositoryInMemory.kt
> +        post = post.copy(
И да, и нет. Ниже приведу сниппет
```kotlin
override val data: MutableLiveData<Post>

init {
     val post = Post(
         ...
     )
    data = MutableLiveData(post)
}

override fun view() {
    val post = checkNotNull(data.value) { // Будет выброшен `IllegalStateException` если `data.value` равен `null` 
        "Какое-нибудь сообщение о том, что `data.value` не должен быть `null`"
    }
    // Более мягкий вариант с молчаливым возвратом из функции вместо падения
    // val post = data.value ?: return
    
    data.value = post.copy(
        views = post.views + 1
    )
}
```
Старайтесь избегать `!!` в коде. Я избежал `!!` фиксированием текущего значения `data.value` в переменной. 
`!!` - выбрасывает `NullReferenceException` в случае провала проверки на `null`. `NRE` так же будет возникать на стыке Kotlin и Java. То есть на стыке "null safety" с "пережитками прошлого" 😊 Лучше пусть приложение будет падать на стыке, где Вы случайно/по невнимательности пропустили `nullable` значение из Java, прописав в Kotlin, что оно `nonnull` (например, переопределили метод Java класса или вызвали метод из Java-кода), чем нарочно валить приложение с помощью `!!`. 
Плюс, Основываясь на Вашем варианте решения, скажу, что совсем не факт, что приложение не свалится на строке `views = data.value!!.views + 1` с учётом того, что команда `data.value?.copy(...)` *казалось бы* прошла проверку на `null`. Всё по причине асинхронной работы современных приложений.

2021-05-07 21:18 UTC, maks1596 requested changes
Обратите внимание на комментарии без "лайков"

2021-05-13 21:17 UTC, maks1596 approved these changes

2021-05-13 21:17 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/repository/PostRepositoryInMemory.kt
> +    }
В чём смысл блока `init`? Если Вы решили не создавать дополнительную временную переменную для удобства чтения для конструируемого `Post`, как я Вам предлагал, то смысл блока `init` теряется. В Вашем запись можно упростить до следующего кода:
```kotlin
override val data = MutableLiveData<Post>(
    Post(
        ...
    )
)
```

2021-05-14 07:31 UTC, merged